menu:
    BLOG: /blog/
    github: https://github.com/enjoychan
    about me: http://enjoychan.github.io/resume/

favicon: /blog/favicon.jpg
logo: /blog/page_bg.jpg

# comment
# e.g disqus: seansun
disqus:
duoshuo:

# google-analytics:
#ga: UA-65933410-1
# baidu-analytics:
#ba: //hm.baidu.com/hm.js?a36e15d9e2adec9a21fcdd9f686b1ed2
